name: ID UPDATE

on:
  schedule:
     - cron: "0 0 * * *"   
     - cron: "0 1 * * *"
     - cron: "0 2 * * *"
     - cron: "0 3 * * *"
     - cron: "0 4 * * *"
     - cron: "0 5 * * *"
     - cron: "0 6 * * *"
     - cron: "0 7 * * *"
     - cron: "0 8 * * *"
     - cron: "0 9 * * *"
     - cron: "0 10 * * *"
     - cron: "0 11 * * *"
     - cron: "0 12 * * *"
     - cron: "0 13 * * *"
     - cron: "0 14 * * *"
     - cron: "0 15 * * *"
     - cron: "0 16 * * *"
     - cron: "0 17 * * *"
     - cron: "0 18 * * *"
     - cron: "0 19 * * *"
     - cron: "0 20 * * *"
     - cron: "0 21 * * *"
     - cron: "0 22 * * *"
     - cron: "0 23 * * *"
  workflow_dispatch:        

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas requests "snowflake-connector-python[pandas]"

      - name: Run script
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          WAREHOUSE: ${{ secrets.WAREHOUSE }}
          DATABASE: ${{ secrets.DATABASE }}
          SCHEMA: ${{ secrets.SCHEMA }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TABLE_NAME1: ${{ secrets.TABLE_NAME1 }}
          TABLE_NAME2: ${{ secrets.TABLE_NAME2 }}
          TABLE_NAME3: ${{ secrets.TABLE_NAME3 }}
        run: python fetch_ids.py